[package]
name = "rusty_time"
version = "0.12.0"
edition = "2021"
description = "A simple timer"
homepage = "https://github.com/cleancut/rusty_time"
repository = "https://github.com/cleancut/rusty_time"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
